source "https://rubygems.org"
ruby "2.1.2"
gem "rails", "4.1.1"
gem "pg"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.0.0"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "nokogiri"
gem "sexmachine", "~> 0.1.0"
gem "delayed_job_active_record"
gem "rails_12factor"
