# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3379ed0d0732e842e6b9976908341d160316a910fb95fff13e0183f0a79c257223a9a3e7836d0b33747b0977ad6b088d4851db082cac269af1239c345d901b99

test:
  secret_key_base: 8b11e16a308cc6ac76646781982890822d208fcd8e8f96a39d19561f50d478120d4654c36784e4d190ea4623b45e521986d7bf37398a30e578cff61f16219fdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
